FROM ubuntu:bionic AS base
ENV TZ=Etc/UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt update && apt upgrade -y && \
    apt-get install -y curl git-core pkg-config autoconf libtool automake \
                   faketime bsdmainutils ca-certificates python3 bison
