FROM ubuntu:xenial AS base
RUN apt-get update && apt-get upgrade && \
    apt-get install -y curl g++-aarch64-linux-gnu g++-4.8-aarch64-linux-gnu \
                gcc-4.8-aarch64-linux-gnu binutils-aarch64-linux-gnu \
                g++-arm-linux-gnueabihf g++-4.8-arm-linux-gnueabihf \
                gcc-4.8-arm-linux-gnueabihf binutils-arm-linux-gnueabihf \
                g++-4.8-multilib gcc-4.8-multilib binutils-gold git-core \
                pkg-config autoconf libtool automake faketime bsdmainutils \
                ca-certificates python3
